import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { decodeJsonDocument, type LosslessJsonValue } from "@bdp/protocol";
import { afterAll, expect, it } from "vitest";
import { schemaSpans, instanceSpans } from "../test-support/schema-graph-spans.js";
import {
  CONTRACT_ARTIFACT_CEILINGS,
  type ContractArtifactInput,
} from "./installed-contract-artifact.js";
import {
  GraphBudget,
  isSchemaObject,
  SCHEMA_GRAPH_CEILINGS,
  SchemaGraphError,
  visitSchemaChildren,
} from "./installed-schema-shape.js";
import { resolveSchemaUri } from "./installed-schema-uri.js";
import {
  compilePrivateSchemaEvaluator,
  EVALUATOR_CEILINGS,
  type CompilationOutcome,
  type EvaluationOutcome,
} from "./installed-schema-evaluator.js";
const inputIntegrity = {
  manifest: false,
  fileHashes: false,
  schemaSpans: false,
  instanceSpans: false,
};
const root = new URL("../test-support/schema-graph-corpus/", import.meta.url);
const manifest: {
  files: { path: string; sha256: string }[];
  groups: { file: string; group: number; graphDisposition: string; reason: string }[];
  cases: { file: string; group: number; case: number; officialValid: boolean }[];
} = JSON.parse(readFileSync(new URL("manifest.json", root), "utf8"));
const hash = (text: string | Uint8Array) => createHash("sha256").update(text).digest("hex");
type ExpectedDisposition =
  | { readonly disposition: "official-validity-compared" | "annotation-policy-outcome" }
  | {
      readonly disposition: "explicit-private-refusal" | "retained-graph-refusal";
      readonly phase: "compile" | "instance";
      readonly reason: string;
    };
const expectedManifest: {
  originalManifestSha256: string;
  groups: (ExpectedDisposition & { file: string; group: number; cases: number[] })[];
} = JSON.parse(
  readFileSync(
    new URL("../test-support/schema-evaluator-dispositions.json", import.meta.url),
    "utf8",
  ),
);
// This separately reviewed oracle is fixed input, never regenerated by a test run.
// The original manifest digest pins case identities and official expected flags.
if (hash(readFileSync(new URL("manifest.json", root))) !== expectedManifest.originalManifestSha256)
  throw new Error("changed original corpus manifest; review the private evaluator oracle");
inputIntegrity.manifest = true;
const caseKey = (c: { file: string; group: number; case: number }) =>
  JSON.stringify([c.file, c.group, c.case]);
const expectedByCase = new Map<string, ExpectedDisposition>();
for (const group of expectedManifest.groups)
  for (const caseIndex of group.cases) {
    const key = caseKey({ ...group, case: caseIndex });
    if (expectedByCase.has(key)) throw new Error(`duplicate private evaluator expectation ${key}`);
    expectedByCase.set(key, group);
  }
function assertExpectedOutcome(
  expected: ExpectedDisposition,
  outcome: CompilationOutcome | EvaluationOutcome,
): void {
  if (
    expected.disposition === "explicit-private-refusal" ||
    expected.disposition === "retained-graph-refusal"
  ) {
    expect(outcome.kind).toBe("refused");
    if (outcome.kind !== "refused") throw new Error("expected a refused evaluator outcome");
    expect(outcome.phase).toBe(expected.phase);
    expect(outcome.reason).toBe(expected.reason);
  } else {
    expect(outcome.kind).toBe("evaluated");
  }
}
const fileText = new Map<string, string>();
for (const file of manifest.files) {
  const bytes = readFileSync(new URL(file.path, root));
  if (hash(bytes) !== file.sha256) throw new Error("changed official corpus");
  fileText.set(file.path, bytes.toString("utf8"));
}
inputIntegrity.fileHashes = true;
const remote = new Map(
  [...fileText]
    .filter(([name]) => name.startsWith("remotes/"))
    .map(([name, text]) => [`http://localhost:1234/${name.slice(8)}`, text]),
);
/** Test-only explicit closure assembly; no loader exists in the production builder. */
function bundle(text: string): ContractArtifactInput[] {
  const uri = "https://corpus.test/root";
  const rows = new Map([[uri, text]]);
  const queue = [{ uri, text }];
  const known = new Set<string>();
  const refs: string[] = [];
  for (let next = 0; next < queue.length; next++) {
    const doc = queue[next];
    if (!doc) throw new Error("corpus queue");
    known.add(doc.uri);
    const budget = new GraphBudget(SCHEMA_GRAPH_CEILINGS);
    const pending = [{ value: decodeJsonDocument(doc.text), base: doc.uri }];
    while (pending.length) {
      const current = pending.pop();
      if (!current) throw new Error("corpus frame");
      if (!isSchemaObject(current.value)) continue;
      let base = current.base;
      if (typeof current.value.$id === "string")
        base = resolveSchemaUri(base, current.value.$id, budget).resource;
      known.add(base);
      for (const k of ["$ref", "$dynamicRef"] as const)
        if (typeof current.value[k] === "string")
          refs.push(resolveSchemaUri(base, current.value[k], budget).resource);
      // Unsupported schema positions still need their original planned refusal,
      // not an attempted execution or custom dialect substitution.
      try {
        visitSchemaChildren(current.value, budget, (c) =>
          pending.push({ value: c.value as LosslessJsonValue, base }),
        );
      } catch (e) {
        if (!(e instanceof SchemaGraphError) || !e.code.startsWith("unsupported-")) throw e;
      }
    }
    for (const ref of refs)
      if (!known.has(ref) && !rows.has(ref)) {
        const body = remote.get(ref);
        if (body !== undefined) {
          rows.set(ref, body);
          queue.push({ uri: ref, text: body });
        }
      }
  }
  return [...rows].map(([retrievalUri, text]) => ({ retrievalUri, utf8Bytes: Buffer.from(text) }));
}

const schemas = new Map(
  [...fileText]
    .filter(([file]) => file.startsWith("tests/"))
    .map(([file, text]) => [file, schemaSpans(text)]),
);
const values = new Map(
  [...fileText]
    .filter(([file]) => file.startsWith("tests/"))
    .map(([file, text]) => [file, instanceSpans(text)]),
);
const compiled = new Map<string, CompilationOutcome>();
const records: Record<string, unknown>[] = [];
it("pins an exact private evaluator disposition for every original case", () => {
  expect(expectedManifest.groups).toHaveLength(462);
  expect([...expectedByCase.keys()].sort()).toEqual(manifest.cases.map(caseKey).sort());
  const counts: Record<string, number> = {};
  for (const expected of expectedByCase.values())
    counts[expected.disposition] = (counts[expected.disposition] ?? 0) + 1;
  expect(counts).toEqual({
    "official-validity-compared": 999,
    "annotation-policy-outcome": 859,
    "explicit-private-refusal": 406,
    "retained-graph-refusal": 58,
  });
});
it.each(["official-validity-compared", "annotation-policy-outcome"] as const)(
  "oracle rejects an unexpected refusal for an expected %s case",
  (disposition) => {
    const expected = [...expectedByCase.values()].find((row) => row.disposition === disposition);
    if (!expected) throw new Error("missing supported oracle control");
    for (const reason of ["unsupported-pattern", "limit-work", "input-domain"])
      expect(() =>
        assertExpectedOutcome(expected, {
          kind: "refused",
          stage: "private-static-schema-evaluation-1",
          phase: "instance",
          reason,
        }),
      ).toThrow();
  },
);
it("oracle accepts its expected refusal and rejects changed phase, reason or outcome", () => {
  const expected = [...expectedByCase.values()].find(
    (row) => row.disposition === "explicit-private-refusal",
  );
  if (!expected || !("reason" in expected)) throw new Error("missing refused oracle control");
  const refusal = {
    kind: "refused" as const,
    stage: "private-static-schema-evaluation-1" as const,
    phase: expected.phase,
    reason: expected.reason,
  };
  expect(() => assertExpectedOutcome(expected, refusal)).not.toThrow();
  expect(() =>
    assertExpectedOutcome(expected, {
      ...refusal,
      phase: expected.phase === "compile" ? "instance" : "compile",
    }),
  ).toThrow();
  expect(() => assertExpectedOutcome(expected, { ...refusal, reason: "limit-work" })).toThrow();
  expect(() =>
    assertExpectedOutcome(expected, {
      kind: "evaluated",
      stage: "private-static-schema-evaluation-1",
      valid: true,
      diagnostics: [],
      diagnosticsComplete: true,
      annotations: [],
      counters: EVALUATOR_CEILINGS,
      annotationPolicy: {
        revision: "bounded-annotation-output-2",
        format: "annotation-only",
        contentEncoding: "annotation-only-no-decoding",
        output: "complete-or-refused",
        encodedBytes: "JSON.stringify-UTF8-lossless-number-objects",
        order: "graph-edge-occurrence-order",
      },
      deferred: [
        "full-vocabulary",
        "dynamic",
        "unevaluated",
        "regex",
        "mime",
        "production-work-and-heap",
        "root-openness",
        "receiver",
        "registry",
        "ownership",
      ],
    }),
  ).toThrow();
});
function assertSchemaSpans(
  text: string,
  spans: readonly { start: number; end: number; text: string }[],
  expected: readonly LosslessJsonValue[],
): void {
  expect(spans).toHaveLength(expected.length);
  for (let i = 0; i < spans.length; i++) {
    const span = spans[i];
    if (!span) throw new Error("missing schema span");
    expect(text.slice(span.start, span.end)).toBe(span.text);
    expect(decodeJsonDocument(span.text)).toEqual(expected[i]);
  }
}
it("schema span oracle rejects dropped, shifted and altered schema spans", () => {
  const text = '[{"schema":true,"tests":[]},{"schema":false,"tests":[]}]';
  const spans = schemaSpans(text);
  expect(() => assertSchemaSpans(text, spans, [true, false])).not.toThrow();
  expect(() => assertSchemaSpans(text, spans.slice(1), [true, false])).toThrow();
  expect(() => assertSchemaSpans(text, [...spans].reverse(), [true, false])).toThrow();
  const first = spans[0];
  if (!first) throw new Error("missing control span");
  expect(() =>
    assertSchemaSpans(text, [{ ...first, text: "false" }, spans[1] as typeof first], [true, false]),
  ).toThrow();
});
it("pins every original scalar/schema case span and expected flag", () => {
  expect(manifest.cases).toHaveLength(2322);
  expect(manifest.groups).toHaveLength(462);
  expect(new Set(manifest.cases.map((c) => `${c.file}:${c.group}:${c.case}`)).size).toBe(2322);
  for (const [file, spans] of values) {
    const text = fileText.get(file) as string;
    const parsed = decodeJsonDocument(text) as readonly {
      schema: LosslessJsonValue;
      tests: readonly { data: LosslessJsonValue; valid: boolean }[];
    }[];
    const schemaRows = schemas.get(file);
    if (!schemaRows) throw new Error("missing schema spans");
    expect(schemaRows).toHaveLength(manifest.groups.filter((g) => g.file === file).length);
    assertSchemaSpans(
      text,
      schemaRows,
      parsed.map((g) => g.schema),
    );
    for (const span of spans) {
      expect(text.slice(span.start, span.end)).toBe(span.text);
      expect(decodeJsonDocument(span.text)).toEqual(parsed[span.group]?.tests[span.case]?.data);
    }
    expect(spans.length).toBe(manifest.cases.filter((c) => c.file === file).length);
    for (const c of manifest.cases.filter((c) => c.file === file))
      expect(parsed[c.group]?.tests[c.case]?.valid).toBe(c.officialValid);
  }
  inputIntegrity.schemaSpans = true;
  inputIntegrity.instanceSpans = true;
});
for (const c of manifest.cases)
  it(`${c.file} group ${c.group} case ${c.case}`, () => {
    const key = `${c.file}:${c.group}`;
    const schema = schemas.get(c.file)?.[c.group];
    const value = values.get(c.file)?.find((s) => s.group === c.group && s.case === c.case);
    if (!schema || !value) throw new Error("missing original raw span");
    let compiler = compiled.get(key);
    if (!compiler) {
      compiler = compilePrivateSchemaEvaluator({
        bundle: {
          descriptors: [],
          schemas: bundle(schema.text),
          limits: CONTRACT_ARTIFACT_CEILINGS,
        },
        graphLimits: SCHEMA_GRAPH_CEILINGS,
        entry: { kind: "schema", retrievalUri: "https://corpus.test/root" },
        limits: EVALUATOR_CEILINGS,
      });
      compiled.set(key, compiler);
    }
    const outcome =
      compiler.kind === "compiled"
        ? compiler.evaluateUtf8(new TextEncoder().encode(value.text))
        : compiler;
    const record: Record<string, unknown> = {
      ...c,
      schemaPointer: `/${c.group}/schema`,
      instancePointer: `/${c.group}/tests/${c.case}/data`,
      schemaSha256: hash(schema.text),
      instanceSha256: hash(value.text),
      instanceByteStart: Buffer.byteLength((fileText.get(c.file) as string).slice(0, value.start)),
      instanceByteEnd: Buffer.byteLength((fileText.get(c.file) as string).slice(0, value.end)),
      outcome: outcome.kind,
      ...(outcome.kind === "refused"
        ? { phase: outcome.phase, reason: outcome.reason }
        : { actualValid: outcome.valid, counters: outcome.counters }),
    };
    records.push(record);
    record.expectationMet = false;
    try {
      const group = manifest.groups.find((g) => g.file === c.file && g.group === c.group);
      if (!group) throw new Error("missing group");
      const expected = expectedByCase.get(caseKey(c));
      if (!expected) throw new Error("missing private evaluator expectation");
      record.disposition = expected.disposition;
      assertExpectedOutcome(expected, outcome);
      if (outcome.kind === "refused") {
        expect(group.graphDisposition).toBe(
          expected.disposition === "retained-graph-refusal"
            ? "planned-refusal"
            : "planned-index-support",
        );
        record.expectationMet = true;
        return;
      }
      expect(group.graphDisposition).toBe("planned-index-support");
      if (expected.disposition === "annotation-policy-outcome") {
        expect(c.file).toContain("/optional/format/");
        const parsed = decodeJsonDocument(schema.text) as Record<string, LosslessJsonValue>;
        expect(
          Object.keys(parsed).filter((k) => !["format", "$schema", "description"].includes(k)),
        ).toEqual([]);
        expect(outcome.valid).toBe(true);
      } else {
        expect(expected.disposition).toBe("official-validity-compared");
        expect(outcome.valid).toBe(c.officialValid);
      }
      record.expectationMet = true;
    } catch (error) {
      record.failure = "case-expectation-mismatch";
      throw error;
    }
  });
afterAll(() => {
  const output = process.env.BDP_PRIVATE_SCHEMA_CORPUS_RECEIPT;
  if (output)
    writeFileSync(
      output,
      `${JSON.stringify(
        {
          stage: "private-static-instance-results-1",
          evidencePolicy: "case-expectations-and-input-integrity-2",
          verificationScope:
            "Case assertions and input integrity; runner test report remains authoritative for the full suite",
          inputIntegrity: { ...inputIntegrity },
          officialInputsUnchanged: inputIntegrity.manifest && inputIntegrity.fileHashes,
          allExpectationsMet:
            Object.values(inputIntegrity).every(Boolean) &&
            records.length === manifest.cases.length &&
            records.every((r) => r.expectationMet === true),
          expectedCases: manifest.cases.length,
          recordedCases: records.length,
          failedCases: records.filter((r) => r.expectationMet !== true).length,
          records,
        },
        null,
        2,
      )}\n`,
    );
  expect(records).toHaveLength(2322);
});
